### ISSUE TITLE
Undefined index: year

### ISSUE THREAD

**Issue by nassajis** [morilog/jalali#10]
ErrorException in jDateTime.php line 735: Undefined index: year

echo jDateTime::createDateTimeFromFormat('Y/m/d h:i:s', "1395/4/15 00:00:00"); //error
echo jDateTime::createDateTimeFromFormat('Y/m/d h:i:s', "1395/04/15 00:00:00"); //success

Error because length of month or day

**Comment by morilog** [comment]
your response is in your question, see [here](http://php.net/manual/en/function.date.php) for more info.
