### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable 

### ISSUE THREAD

**Issue by saber13812002** [morilog/jalali#102]
composer require morilog/jalali
Using version ^3.1 for morilog/jalali
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package jeremeamia/SuperClosure is abandoned, you should avoid using it. Use opis/closure instead.
Package mtdowling/cron-expression is abandoned, you should avoid using it. Use dragonmantank/cron-expression instead.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
> php artisan clear-compiled
> php artisan optimize
Generating optimized class loader

PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in C:\Users\saber\saberprojects\hajihosseini\dingo-project-management\vendor\symfony\process\Pipes\WindowsPipes.php:221
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', 'C:\\Users\\saber\\...', 221, Array) 
#1 C:\Users\saber\saberprojects\hajihosseini\dingo-project-management\vendor\symfony\process\Pipes\WindowsPipes.php(221): count(NULL)
#2 C:\Users\saber\saberprojects\hajihosseini\dingo-project-management\vendor\symfony\process\Pipes\WindowsPipes.php(112): Symfony\Component\Process\Pipes\WindowsPipes->write(false, false)
#3 C:\Users\saber\saberprojects\hajihosseini\dingo-project-management\vendor\symfony\process\Process.php(1322): Symfony\Component\Process\Pipes\WindowsPipes->readAndWrite(false, false)
#4 C:\Users\saber\saberprojects\hajihosseini\dingo-project-management\vendor\symfony\process\Process.php(1260): Symfony\Component\Proces in C:\Users\saber\saberprojects\hajihosseini\dingo-project-management\vendor\symfony\process\Pipes\WindowsPipes.php on line 221
PHP Stack trace:
PHP   1. {main}() C:\Users\saber\saberprojects\hajihosseini\dingo-project-management\artisan:0

  [ErrorException]
  count(): Parameter must be an array or an object that implements Countable

Script php artisan optimize handling the post-update-cmd event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by saber13812002** [comment]
composer require morilog/jalali:3
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for morilog/jalali 3 -> satisfiable by morilog/jalali[v3.0.0].
    - morilog/jalali v3.0.0 requires beberlei/assert dev-master -> satisfiable by beberlei/assert[dev-master] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.

**Comment by morilog** [comment]
Use latest version of `morilog/jalai`. currently is `v3.1.2`
