### ISSUE TITLE
آپدیت از ورژن ۲ به ۳

### ISSUE THREAD

**Issue by onlinearash** [morilog/jalali#108]
با سلام
برای آپدیت از ورژن ۲ به ۳ باید چه رویه‌ای را انجام داد؟

**Comment by morilog** [comment]
فقط تو composer.jsonباید تغییر بدی
واینکه هیچ backward-compatiblity نداره از ۲ به ۳
یعنی باید هر جا استفاده میکردی با apiجدید استفاده کنی
