### ISSUE TITLE
error in install php8 laravel 8

### ISSUE THREAD

**Issue by roshandelpoor** [morilog/jalali#116]
hi
Thanks For This Package.
I have this error on install laravel 8 and php 8

- beberlei/assert[v3.0.0, ..., v3.x-dev] require php ^7 -> your php version (8.0.1) does not satisfy that requirement.
- beberlei/assert[v3.3.0-beta1, ..., v3.3.0] require ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.

**Comment by FaridAghili** [comment]
Make sure you have `ext-intl` enabled in your `php.ini`:

![image](https://user-images.githubusercontent.com/8607021/107629801-e1cabb80-6c77-11eb-8bd9-30434f6cf80e.png)

**Comment by roshandelpoor** [comment]
thanks
