### ISSUE TITLE
مشکل در php 8

### ISSUE THREAD

**Issue by MohammadBadzohreh** [morilog/jalali#119]
سلام خسته نباشید من 
php8
رو نصب کردم و لی وقتی دستور composer update
رو میزنم متاسفانه هین پکیج گیر میده که پی اچ پی باید ورژن 7 تا 7.3 باشه میخواستم بدونم  که این پکیج با پی ا چ پی ورژن 8 سازگار هست یا خیر؟

**Comment by parsasamandi** [comment]
سلام وقتتون بخیر
توی composer.json 
بخش require
"php": "^7.3|^8.0",
فکر میکنم مشکلتون حل بشه

**Comment by MohammadBadzohreh** [comment]
اینکارم کردم متاسفانه حل نشد

**Comment by parsasamandi** [comment]
متاسفم چون ورژن پی اچ پی من هم هشت هستش، و کار میکنه
اگر ارور رو کامل بفرستید فکر میکنم بهتر بتونم کمکتون کنم

**Comment by amirhossein-shakeri-work** [comment]
سلام. پکیج واقعا عالی هست فقط برای من هم هنگام نصب ارور داد واقعا خیلی برام مهمه لطفا راهنمایی کنید

خطا رو به صورت کامل پایین میفرستم

```bash
composer require morilog/jalali:3.*  
./composer.json has been updated
Running composer update morilog/jalali
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - morilog/jalali v3.2.0 requires beberlei/assert 3.* -> satisfiable by beberlei/assert[v3.0.0, ..., v3.x-dev].
    - morilog/jalali[v3.0.0, ..., v3.0.2] require illuminate/support ^5.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - morilog/jalali[v3.0.3, ..., v3.0.8] require nesbot/carbon ^1.21 -> found nesbot/carbon[1.21.0, ..., 1.39.1] but the package is fixed to 2.46.0 (lock file version) by a partial update and that version does not 
match. Make sure you list it as an argument for the update command.
    - morilog/jalali v3.0.9 requires php ^7.0 -> your php version (8.0.3) does not satisfy that requirement.
    - morilog/jalali[v3.0.10, ..., v3.1.2] require php ^7.0 | ^7.1 | ^7.2 -> your php version (8.0.3) does not satisfy that requirement.
    - beberlei/assert[v3.0.0, ..., v3.x-dev] require php ^7 -> your php version (8.0.3) does not satisfy that requirement.
    - beberlei/assert[v3.3.0-beta1, ..., v3.3.0] require ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.
    - Root composer.json requires morilog/jalali 3.* -> satisfiable by morilog/jalali[v3.0.0, ..., v3.2.0].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by amirhossein-shakeri-work** [comment]
> سلام. پکیج واقعا عالی هست فقط برای من هم هنگام نصب ارور داد واقعا خیلی برام مهمه لطفا راهنمایی کنید
> 
> خطا رو به صورت کامل پایین میفرستم
> 
> ```shell
> composer require morilog/jalali:3.*  
> ./composer.json has been updated
> Running composer update morilog/jalali
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - morilog/jalali v3.2.0 requires beberlei/assert 3.* -> satisfiable by beberlei/assert[v3.0.0, ..., v3.x-dev].
>     - morilog/jalali[v3.0.0, ..., v3.0.2] require illuminate/support ^5.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
>     - morilog/jalali[v3.0.3, ..., v3.0.8] require nesbot/carbon ^1.21 -> found nesbot/carbon[1.21.0, ..., 1.39.1] but the package is fixed to 2.46.0 (lock file version) by a partial update and that version does not 
> match. Make sure you list it as an argument for the update command.
>     - morilog/jalali v3.0.9 requires php ^7.0 -> your php version (8.0.3) does not satisfy that requirement.
>     - morilog/jalali[v3.0.10, ..., v3.1.2] require php ^7.0 | ^7.1 | ^7.2 -> your php version (8.0.3) does not satisfy that requirement.
>     - beberlei/assert[v3.0.0, ..., v3.x-dev] require php ^7 -> your php version (8.0.3) does not satisfy that requirement.
>     - beberlei/assert[v3.3.0-beta1, ..., v3.3.0] require ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.
>     - Root composer.json requires morilog/jalali 3.* -> satisfiable by morilog/jalali[v3.0.0, ..., v3.2.0].
> 
> To enable extensions, verify that they are enabled in your .ini files:
>     - C:\xampp\php\php.ini
> You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.
> ```
> 
> تا حد امکان نمیخوام پکیج هایی که دارم downgrade بشن میخوام آپدیت باشن
> میشه یه جوری حلش کرد؟
> 
> من از لاراول ۸ و پی اچ پی ۸ استفاده میکنم



پس از اجرای دستور 
`composer update`
مشکل حل شد
