### ISSUE TITLE
Missing "format characters"

### ISSUE THREAD

**Issue by mdaliyan** [morilog/jalali#12]
Hi,

According to this page [function.date.php](http://php.net/manual/en/function.date.php), some other **format characters** like u and v exist that are not supported by  _Jalali_ .

```
$d1 =  DateTime::createFromFormat('Y-m-d H:i:s.u', '1966-02-31 22:32:11.254687'); //success
$d2 = jDateTime::createFromFormat('Y-m-d H:i:s.u', '1354-02-31 22:32:11.254687');; //error
```
I don't want to hard code _Jalali_. May you please consider adding missing **format characters** to  _Jalali_ ?

**Comment by morilog** [comment]
supporting of all date chars is in progress...

**Comment by mdaliyan** [comment]
Thank you very much. May you please [close this issue using commit massage](https://help.github.com/articles/closing-issues-via-commit-messages/) so I'll be notified?
