### ISSUE TITLE
 مشکل سال کبیسه برای نشان دادن ماه قبل

### ISSUE THREAD

**Issue by shahramfdl** [morilog/jalali#120]
سلام
وقتی از forge("last month") استفاده میکنم اشتباها اولین روز همین ماه رو نشون میده.
سال کبیسه رو تشخیص نداده.
به عبارت دیگه forge("0 month") رو داره درست نشون میده و روی forge("-1 month") مشکل داره

**Comment by morilog** [comment]
از متد subMonth استفاده کنید

**Comment by shahramfdl** [comment]
ممنون از پاسختون
من این روش رو استفاده کردم
```
list($yearNow, $monthNow, $dayNow) = explode('/', Jalalian::now()->format('Y/m/d'));
$jalalian = new Jalalian($yearNow, $monthNow, $dayNow);
```
چند تا مشکل دارم
اول اینکه من لیست ماه ها رو میخوام بدست بیارم و ماه فعلی رو نمیتونم با subMonths(0) در بیارم خطا میگیرم
`$jalalian->subMonths($i)->format('m Y')`

دومین مشکلی که هست برای بدست آوردن هفته ها قبلا از این روش استفاده میکردم
`Jalalian::forge("-$i week")->format('W Y')`

و subWeeks نداریم

چه راهی رو شما پیشنهاد میکنید؟

**Comment by morilog** [comment]
به جای subweeks میتونی از subDays استفاده کنی. همه جا طول هفته ۷ روزه
