### ISSUE TITLE
Add support for Afghan month

### ISSUE THREAD

**Issue by ahangarha** [morilog/jalali#126]
Afghans use different names for month. The calendar is exact same but names are different.

It would be great if there be a way to specify what kind of names to use for months.

Names are as such:
 - حمل
 - ثور
 - جوزا
 - سرطان
 - اسد
 - سنبله
 - میزان
 - عقرب
 - قوس
 - جدی
 - دلو
 - حوت

More info: https://en.wikipedia.org/wiki/Solar_Hijri_calendar

**Comment by morilog** [comment]
This has been added at `v3.4.0` 
You can use between `CalendarUtils::useAfghanMonthsName()` and `CalendarUtils::useIranianMonthsName()`
