### ISSUE TITLE
سال های حیوانی

### ISSUE THREAD

**Issue by omidMolaverdi** [morilog/jalali#129]
با سلام و تشکر از شما،
من از کتابخونه شما خیلی استفاده کردم و خیلی عالی هست ولی بعضی توابع در `jdate` را ندارد.

بعنوان مثال کلید 

نام باستانی برج ها | p

پلنگ | گاو | موش تا خوک | نام حیوانی سال ها | q

در کتابخانه وجود ندارد. لطفا در مورد اضافه کردن این موارد راهنمایی می فرمایید؟

**Comment by morilog** [comment]
فعلن نیازی به این مقادیر نبوده اگه نیازی میبینید ممنون میشه مرج ریکوئست بفرستید برای این کار
