### ISSUE TITLE
مشکل نمایش هفته از سال

### ISSUE THREAD

**Issue by qmeyti** [morilog/jalali#132]
سلام. وقت بخیر.

بنظر میرسه وقتی که برای فرمت خروجی W رو وارد کنیم و بخواییم که هفته از سال رو نشون بده سیستم خطا وجود داره.

**Comment by morilog** [comment]
این خروجی توی این ورژن ساپورت نمیشه. در ورژن‌‌های آینده سعی میشه تمام پارامترهای ممکن برای فورمت کردن پشتیبانی بشه
