### ISSUE TITLE
Class "Morilog\Jalali\Jalalian" not found

### ISSUE THREAD

**Issue by hamirad** [morilog/jalali#133]
i was install v3 of jalali and  use `\Morilog\Jalali\Jalalian::now()`  for display my time in my project
 but its not work 
![sa](https://user-images.githubusercontent.com/94746833/142727461-7c912146-7d44-4dfc-9c7e-5d0cdb24fec7.jpg)

.

**Comment by morilog** [comment]
It seems the package does not installed properly. Please try `composer update` or `composer install` again.
