### ISSUE TITLE
php 8.1 deprecation

### ISSUE THREAD

**Issue by mziraki** [morilog/jalali#135]
problem:
"Implicit conversion from float x to int loses precision" warning

solution:
https://php.watch/versions/8.1/deprecate-implicit-conversion-incompatible-float-string

**Comment by mhyeganeh** [comment]
![Annotation 2022-03-17 110006](https://user-images.githubusercontent.com/32367934/158758707-94fe2fd9-193e-44e2-bd3e-550c01de23d0.jpg)

PHP V8.1.3
morilog/jalali V3.2.0

**Comment by mziraki** [comment]
@mhyeganeh looks like this package is abandoned, I suggest using this package: https://github.com/hekmatinasser/verta

**Comment by mhyeganeh** [comment]
@mziraki I don't think this package is abandoned... And I hope new release will be published any time soon since the problem has been resolved here #139

**Comment by mziraki** [comment]
@mhyeganeh has been patched under wrong package name! "moree-dev/jalali"

**Comment by mhyeganeh** [comment]
@morilog 
Thanks for you efforts and your perfect package. Please explain what's happened in #139 and should we wait for new release of morilog/jalali or is it actually abandoned...?
