### ISSUE TITLE
Modify on dates

### ISSUE THREAD

**Issue by mdaliyan** [morilog/jalali#14]
I saw on the codes that `reforge` is actually same as `modify`. So I tried this:

```
 $c = jDate::forge( Carbon::createFromDate(2016,12,1)->timestamp );
 $this->assertSame('1395-09-11', $c->format('Y-m-d'));

 $c->reforge('2 month');
 $this->assertSame('1395-11-11', $c->format('Y-m-d'));
```
and got this:

> Failed asserting that two strings are identical.
> --- Expected
> +++ Actual
> @@ @@
> -1395-11-11
> +1395-11-13

Are you planning to add this functionality to Jalali dates soon? I mean if you are already working on it I'll wait. Or if you're not, I figure it out somehow and make a PR for morilog/jalali.

**Comment by morilog** [comment]
`forge` and `reforge` and every methods in this package has work with `DateTime` instance (gregorian date), there is no library for working with jalali date. Make a PR if you interested.
