### ISSUE TITLE
Slowness package on Laravel 9

### ISSUE THREAD

**Issue by hasanmonfared** [morilog/jalali#142]
Hi, I used this package in the project and
I have this warning
And it works very, very slowly
Laravel version: 9.5
PHP version:8.1
Warning message:
LOG.warning: Implicit conversion from float -0.8333333333333334 to int loses precision in /var/www/html/vendor/morilog/jalali/src/CalendarUtils.php on line 209

[10:31:37] LOG.warning: Implicit conversion from float 0.4 to int loses precision in /var/www/html/vendor/morilog/jalali/src/CalendarUtils.php on line 209

**Comment by morilog** [comment]
This bug has been fixed at latest version
