### ISSUE TITLE
Not supporting diffForHumans

### ISSUE THREAD

**Issue by mohammadyahia123** [morilog/jalali#148]
At start I wanted to keep working with some notes that needed to be displayed as human readable time difference, but I coyldn't find the persian format of the diffForHuman method of carbon.

**Comment by mhyeganeh** [comment]
You can simply use `diffForHumans()` method of Cabon package by setting disired locale in config/app.php file or dynamically:

```
Carbon::setLocale('fa');
echo $record->created_at->diffForHumans();  //۳ روز پیش
```

**Comment by morilog** [comment]
You can use `ago` method to display human readable and relative datetime
