### ISSUE TITLE
null return

### ISSUE THREAD

**Issue by elyasnajari** [morilog/jalali#158]
سلام وقتی از کد
{!! jdate($item->created_at)->format('%d %B %Y') !!}
استفاده می کنم درست کار میکنه ولی اگر مقدار $item->created_at خالی(null) باشه تاریخ روزجاری رو برمی گردونه و null برنمی گرده

**Comment by morilog** [comment]
خب اگه signiture تابع رو نگاه کنی متوجه میشی که اگه ورودی null باشه now رو در نظر میگیره. درستش اینه که اگه null هست از این تابع استفاده نکنی
