### ISSUE TITLE
امکان تبدیل تاریخ فارسی به تایم استمپ

### ISSUE THREAD

**Issue by mrmmg** [morilog/jalali#170]
با سلام
کار من crawler نویسی است و در برخی از سایت ها تاریخ به صورت یک متن فارسی نوشته می شود. برای مثال: ۰۸:۵۶ بعدازظهر آیا پکیج شما قابلیت تبدیل چنین رشته ای را دارد؟ اصلا چنین چیزی را تبدیل می کند؟

یا به صورت کلی استرینگی همانند
8 فروردین
رو میتونه تبدیل کنه؟ من روشی پیدا نکردم

**Comment by morilog** [comment]
سلام بعضی توکن‌ها رو ساپورت میکنه نسخه فعلی که توی کد CalendarUtils میتونید لیستشو ببینید. در نسخه بعدی سعی میشه حداکثر توکن‌های موجود برای تاریخ و زمان ساپورت بشه. برای تبدیل هم از همون کلاسی که گفتم میتونید استفاده کنید یعنی فرمت تاریخ فارسی رو بدید میتونه parseش کنه

**Comment by morilog** [comment]
<img width="337" alt="image" src="https://github.com/morilog/jalali/assets/4139179/63f350c8-3d23-4914-a336-936d9997227e">
