### ISSUE TITLE
Problem at the current time!

### ISSUE THREAD

**Issue by salehattari** [morilog/jalali#177]
Hello.
When I use the '**now**' method and convert the returned data from the library to a **DateTime**, the output shows a time that **differs** from the current time by more than one hour. This could become **problematic** for larger projects!

**Comment by morilog** [comment]
Can you show me some examples?

**Comment by salehattari** [comment]
![1](https://github.com/user-attachments/assets/c681193f-b10a-4a4f-a33c-3c36013f9ecd)
![2](https://github.com/user-attachments/assets/95ee0e8e-8d94-40ae-97e1-f6cd60802394)

If you look **carefully** at the pictures, you will see that the current time in Iran is 9:18 AM, but the time that the library returns is 7:48 AM!
In another image, I have shown you the code that led to this output for a closer look.

**Comment by morilog** [comment]
did you set timezone to 'Asia/Tehran'?

**Comment by salehattari** [comment]
Isn't the timeZone set to "Asia/Tehran" by default?!

**Comment by salehattari** [comment]
No! I hadn't done this because I thought the library did this by default.

Important to all friends who have encountered my problem:
I was able to fix the problem globally in my project by using the date_default_timezone_set function and setting the time zone to 'Asia/Tehran'.

@morilog **Thanks** for the tip

The final php code that fixed my problem:
```
date_default_timezone_set('Asia/Tehran');
```

**Comment by morilog** [comment]
The default timezone has been set in your php installation `php.ini` configurations. But is different with your installation method. It inherit your server default timezone
