### ISSUE TITLE
loop 5/month for two years

### ISSUE THREAD

**Issue by abosami2000** [morilog/jalali#19]
Hi ,

I want to make a loop for filth day in each month to 2 years

5/1/1395
5/2/1395
5/3/1395
5/4/1395
5/5/1395
5/6/1395
5/7/1395
5/8/1395
5/9/1395
5/10/1395
5/11/1395
5/12/1395
5/1/1396
...

How can I do it by your package?

I use mktime() php in Gregorian date 

thanks

**Comment by morilog** [comment]
A loop on what? every jalali year has 12 months and each month has 31, 30 or 29 days
Do you sure you want to loop?

**Comment by abosami2000** [comment]
I want to use mktime() like php function , to convert it to unix time.

Yes , I want

**Comment by morilog** [comment]
Sorry, i dont understand relation between mktime and loop, but you have some jalali date and want to convert them to unix time.
try this:
```
$jdate = '5/1/1395'
$gdate = Morilog\Jalali\jDateTime::createCarbonFromFormat('j/n/Y', $jdate);
$timestamp = $gdate->timestamp;

```
