### ISSUE TITLE
Wrong Daylight saving time.

### ISSUE THREAD

**Issue by mb-programmer** [morilog/jalali#23]
hello
how we can use daylight saving time?
there is an option to enable? or will it be calculated automatically?
thanks.

**Comment by mb-programmer** [comment]
I figure out something
Before printing the time
`
    $daylight = intval(jdate()->format('I'));
    if ($daylight) {
        $timestamp = $timestamp + 3600;
    }
`

Is it a good approach?

**Comment by morilog** [comment]
Daylight saving time is not a general option in jalali calendar and depend on each country politics.

**Comment by mb-programmer** [comment]
With some testing i realized that if I set timezone correctly it will be auto calculated.
Is there a JavaScript version of this project?

**Comment by morilog** [comment]
jalaali/jalaali-js
