### ISSUE TITLE
Error in PHP7.1

### ISSUE THREAD

**Issue by gdpa** [morilog/jalali#24]
In PHP7.1 i get this error:

> A non well formed numeric value encountered

More information:
I'm using Laravel 5.4 on PHP7.1. It works fine with Laravel 5.4 on PHP5.6

**Comment by morilog** [comment]
I have using laravel 5.4 with php 7.1 too. Can you tell me more details about your code and when this error throwed on?

**Comment by nabi009** [comment]
@gdpa  same issue
