### ISSUE TITLE
toGregorian return type

### ISSUE THREAD

**Issue by meysammahfouzi** [morilog/jalali#25]
Is it possible to have another version of `toGregorian` which returns `date` instead of array? Currently I have to do the following to convert numbers to date:

```
$georgianDate = jDateTime::toGregorian(1370, 2, 20);
$year = $georgianDate[0];
$month = $georgianDate[1];
$day = $georgianDate[2];
$birthdate = date("Y-m-d",strtotime("$year-$month-$day"));
```

**Comment by morilog** [comment]
Yes, It will be possible in another method, If you interested, make a pull request.
