### ISSUE TITLE
Class 'Morilog\Jalali\jDatetime' not found

### ISSUE THREAD

**Issue by HamidDarash** [morilog/jalali#28]
Hi , i am using your bundle in view or blade , I went through this error "Class 'Morilog\Jalali\jDatetime' not found". 
---------
.
.
.
 <tr>
     <th>تاریخ رزرو</th>
     <td>{{  \Morilog\Jalali\jDatetime::strftime('Y-m-d',$reservation->date_reserved) }}</td>
 </tr>
.
.
.
please help me.

**Comment by morilog** [comment]
Becasue class name is `jDateTime`, not `jDatetime`

**Comment by Ghafoorfahim** [comment]
I have the same issue and my class name is JdateTime also have this error.

**Comment by morilog** [comment]
Again. class name is exactly `jDateTime`, not `JdateTime`

**Comment by Ghafoorfahim** [comment]
Dear @morilog can you please check the following code what's wrong I changed everything many times installed but have the same error.
This is my helper function 
`function changeDateFormat($date='')
{
    $is_persian=false;

    if($date && $date !='')
    {
       $dateArray=explode('/', $date);
       if(count($dateArray)<3)
       {
         return Carbon::now();
       }
       if($dateArray[0] !=convert($dateArray[0]))
           $is_persian=true;
       $year=convert($dateArray[0]);
       $month=convert($dateArray[1]);
       $day=convert($dateArray[2]);
       $temp='';    
       if($is_persian)
       {
        $temp= \Morilog\Jalali\jDateTime::createCarbonFromFormat(
            'Y/m/d',$year.'/'.$month.'/'.$day);
        $mydate=Carbon::now();
        $mydate->year=$temp->year;
        $mydate->month=$temp->month;
        $mydate->day=$temp->day;
        $temp=$mydate;
        }
        else
        {
            //$temp=Carbon::create($year,$month,$day,1);
            $mydate=Carbon::now();
            $mydate->year=$year;
            $mydate->month=$month;
            $mydate->day=$day;
            $temp=$mydate;
        }
        if($type)
        {   
            
        }
       if($report !='' && $report)
        {
            return $temp->format('Y-m-d');
        }
        else
        {
            return $temp;
        }
    
    //return strtotime($temp->addDay(1));
    }
    else
    {
        return $date;
    }
}`
And check from controller like this:
`$date = Carbon::now();
        if ($request->get('date') != '') {
              $date= changeDateFormat($request->get('date'));
        }`

**Comment by morilog** [comment]
There is no any `ServiceProvider`, `jDate` or `jDateTime` facades.
After version 3 this library is framework-agnostic 
Please read the version 3 documentations
