### ISSUE TITLE
checkdate always returns false

### ISSUE THREAD

**Issue by Palvaneh** [morilog/jalali#3]
jDateTime.checkdate returns false (for any input parameters!)

I replaced function body with original jdf checkdate and it works good
`
    public static function checkdate($jm, $jd, $jy)
    {
        $l_d=($jm==12)?(($jy%33%4-1==(int)($jy%33*.05))?30:29):31-(int)($jm/6.5);
        return($jm>0 and $jd>0 and $jy>0 and $jm<13 and $jd<=$l_d)?true:false;
    }
`

**Comment by morilog** [comment]
good. can you send a pull request?

**Comment by morilog** [comment]
In version `2.0` this bug is fixed.

**Comment by omer-jan** [comment]
Hi Dears,
please help 
echo(\Morilog\Jalali\CalendarUtils::checkDate(1391, 2, 30, true));
echo(\Morilog\Jalali\CalendarUtils::checkDate(2019, 2, 30, true));
 according to documentation the first line should return true and the second line should return false but both return true .
