### ISSUE TITLE
Warning: date_default_timezone_get()

### ISSUE THREAD

**Issue by setareSorbi** [morilog/jalali#35]
I use laravel5.4.I install jalali package.now when I run project, I see this message
 **Whoops, looks like something went wrong.** 
to understand  the details entered this command in terminal 
**php artisan key generate**
  and I got this warning  Warning: 
**date_default_timezone_get(): Invalid  date.timezone value 'Asia/Iran', we selected the timezone 'UTC' for now.  in C:\wamp\www\laravel\vendor\monolog\monolog\src\Monolog\Logger.php on  line 311 Warning: date_default_timezone_get(): Invalid date.timezone value  'Asia/Iran', we selected the timezone 'UTC' for now. in  C:\wamp\www\laravel\vendor\monolog\monolog\src\Monolog\Logger.php on  line 311   [Symfony\Component\Debug\Exception\FatalThrowableError]   Undefined constant 'Morilog\Jalali\JalaliServiceProvider'  timezone of php.ini and app.php is UTC . what should I do to fix this bug?**

**Comment by morilog** [comment]
There is no timezone 'Asia/Iran'. you should use 'Asia/Tehran' instead.
