### ISSUE TITLE
mismatch datetime

### ISSUE THREAD

**Issue by Palvaneh** [morilog/jalali#4]
ساعت نشان داده شده همواره 4:30 از ساعت ذخیره شده عقب است.
my server timezone is Asia/Tehran
my timezone in config/app.php is Asia/Tehran

code to save date:
`jDateTime::createCarbonFromFormat('Y-n-j', $request->input('hire_date'))->toDateString()`

code to show date:
`jDate::forge($user->hire_date)->format('j F Y')`

**Comment by morilog** [comment]
میتونی یه تست براش بنویسی؟

**Comment by hafezdivandari** [comment]
I created pull request #5 for this issue but I think other methods like `jDate()->format` should also be rewritten to support Timezone.

**Comment by morilog** [comment]
@Palvaneh Your fault is because using `toDateString()` method of `carbon`, you should use `toDateTimeString()` instead if this.

I wrote some [tests](https://github.com/morilog/jalali/blob/master/tests/jDateTimeTest.php#L66), you can run and check it.

**Comment by hafezdivandari** [comment]
When I set timezone by adding this command line:
`before-script: echo 'date.timezone = "Asia/Tehran"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini` to my `.travis.yml`, several tests fails because of mismatched timezone.

I have the same problem on my server where I've set timezone to 'Asia/Tehran'.

**Comment by amirhosseini95** [comment]
I have same problem with timezone.
`jDate::forge()->format('datetime')` returns '1395-03-30 09:35:43' instead '1395-03-30 14:05:43'

**Comment by morilog** [comment]
@amirhosseini95 what is your default timezone? can you write a test?

**Comment by hafezdivandari** [comment]
I wrote a test and possible alternative to use: #8

**Comment by amirhosseini95** [comment]
Both of ubuntu and laravel timezone are Asia/Tehran
