### ISSUE TITLE
Class JalaliServiceProvider not found

### ISSUE THREAD

**Issue by ali-mhz** [morilog/jalali#43]
Hi
I'm using laravel 5.4 to develop an app, when i run:
`php artisan optimize`
i got this error:
```
In ProviderRepository.php line 208:
  Class 'Morilog\Jalali\JalaliServiceProvider' not found
```

just to mention that i cloned my project and run this that at the end when it want to optimize i got the above error
`composer install --no-dev`

**Comment by morilog** [comment]
See your composer.json in `require` section, and look for `morilog/jalali` dependency

**Comment by hamid80386** [comment]
my composer.json has 

> "morilog/jalali": "3.*",

and get same error

**Comment by morilog** [comment]
There is not any ServiceProvider from v3. Please read the documentations.

**Comment by peymanator** [comment]
In the documentation in your website you wrote serviceprovider.
سپس فایل config/app.php رو باز کرده و مقادیر زیر رو در آرایه‌های خودشون قرار می‌دیم:

**Comment by HashemiBiBug** [comment]
updated from v2 to v3 and get same error

**Comment by Kamandlou** [comment]
remove Morilog\Jalali\JalaliServiceProvider::class from app.php
