### ISSUE TITLE
set jDate for timestamp field type in laravel

### ISSUE THREAD

**Issue by f4h4m** [morilog/jalali#46]
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1397-06-23 11:45:30' for column 'updated_at' at row 1 (SQL: update `products` set `updated_at` = 1397-06-23 11:45:30 where `id` = 26)

and i don't wanna change the timestamp type to datetime in my table

**Comment by morilog** [comment]
You must store datatime as Gregorian calendar type, use jalali calendar only for displaying in views or reports.
for example:

```php
$product->created_at = jDateTime::createCarbonFromFormat('Y-m-d H:i:s', '1397-06-23 11:45:30');
$product->save();
```
