### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by hamidHeidarinia** [morilog/jalali#47]
Why Version 3 is not installed in LARAVEL version 5.6 and 5.7?

**Comment by morilog** [comment]
It required `php >= 7` and does not any dependency to laravel neither any other frameworks

**Comment by hamidHeidarinia** [comment]
My php version 7.2.9. On Laravel versions 5.6 and 5.7, using the composer require morilog / jalali: 3. * This package could not be installed. But using the composer require morilog / jalali: 2. * it was installed.

Why ?

**Comment by morilog** [comment]
How can not installed? what kind of error or exceptions occurred.
notice: in version 3 there is not any ServiceProvider, Laravel facade or something else.
