### ISSUE TITLE
مشکل در subMonths

### ISSUE THREAD

**Issue by mavinoo** [morilog/jalali#48]
بعد از به روز رسانی فقط به خاطر
`subMonths`
به مشکل برخوردم که درست کار نمیکنه !

مثلا مقدار 1 رو میدم که یک ماه گذشته رو بیاره که دو سه ماه آینده رو میاره.
وقت کردی فیکسش کن.

ممنون

**Comment by morilog** [comment]
میشه بدونم ورودی و خروجی‌هات چیا بودن؟ مثلا از چه تاریخی یه ماه کم کردی؟

**Comment by mavinoo** [comment]
برای همین امروز

`$date = \Morilog\Jalali\Jalalian::now()->subMonths(1);`

`dd($date);`

```
Jalalian {#16 ▼
  -year: 1397
  -month: 11
  -day: 30
  -hour: 6
  -minute: 58
  -second: 35
  -timezone: DateTimeZone {#17 ▶}
}
```

**Comment by morilog** [comment]
روی ورژن 3.0.11 فیکس شد این باگ
