### ISSUE TITLE
Problem with 'forge'

### ISSUE THREAD

**Issue by sajaddp** [morilog/jalali#49]
Hi,
On version 3, when i using `Jalalian::forge(1538902714)` i got below error:
`DateTime::__construct(): Failed to parse time string (1538902714) at position 8 (1): Unexpected character`

Can you help me?

**Comment by morilog** [comment]
It's a bug and i will fix it as soon as possible.
temporary solution:
`Jalalian::forge(date('Y-m-d H:i:s', 1538902714))`

**Comment by iBelit** [comment]
just add this in forge function and createfromCarbon function:
`if(check if is int)
    {
      $time = \Carbon\Carbon::createFromTimestamp($time);
    }`
