### ISSUE TITLE
first day of last month

### ISSUE THREAD

**Issue by Hesammousavi** [morilog/jalali#56]
how can i have this result  ?
`
$date = Jalalian::forge('first day of last month');
// present time for example :  1397-08-08  
// output : 1397-07-01 
`

**Comment by morilog** [comment]
because `forge` method calls Gregorian calendar first day of month then converts the datetime to jalali datetime. it's good to kill this method

**Comment by Hesammousavi** [comment]
i think somehow you should fix it or add this feature
of course if it's possible to fix

**Comment by pouyasalimi** [comment]
$lastMonth = Jalalian::forge("last month", new \DateTimeZone('UTC'))->format('Y/m/01 00:00:00');
