### ISSUE TITLE
predefined format doesn't work

### ISSUE THREAD

**Issue by mhonarvar18** [morilog/jalali#57]
hi
these codes:
// get a predefined format
$date = Jalalian::forge('last sunday')->format('datetime'); // 1391-10-02 00:00:00
$date = Jalalian::forge('last sunday')->format('date'); // 1391-10-02
$date = Jalalian::forge('last sunday')->format('time'); // 00:00:00

doesn't work.
error:

(1/1) InvalidArgumentExceptionUnexpected data found.Unexpected data found.The separation symbol could not be foundA two digit second could not be found
--

**Comment by ikosar** [comment]
@morilog 
$date = Jalalian::forge('yesterday')->format('date'); 
when i run second line i get this date "18ق.ظ30Asia/tehran" what is it?

**Comment by morilog** [comment]
@ikosar 
because this is a missed featured from last version i forget to implement and still a bug. i will fixed it as soon as possible. BTW you can use `format('Y-m-d H:i:s')` instead of that
