### ISSUE TITLE
Fix Documentation

### ISSUE THREAD

**Issue by immeyti** [morilog/jalali#60]
What is the difference?!!

// get relative 'ago' format
$date = Jalalian::forge('now - 10 minutes')->ago() // 10 دقیقه پیش
// OR
$date = Jalalian::forge('now - 10 minutes')->ago() // 10 دقیقه پیش

**Comment by morilog** [comment]
There is no any difference. That's my fault as i wrote documentation

**Comment by immeyti** [comment]
Thanks, So i just fixed it at #75.
