### ISSUE TITLE
Regex problem on parseFromFormat method from CalendarUtils class

### ISSUE THREAD

**Issue by dena-a** [morilog/jalali#63]
The Exception is on line 735.

Exception Message:
> preg_match(): Compilation failed: two named subpatterns have the same name at offset 50

Exception trace:
> preg_match("#^(?P<year>\d{4})/(?P<month>[A-Z][a-z]{3})(?P<month>[A-Z][a-z]{3})/(?P<day>[A-Z][a-z]{2})(?P<day>[A-Z][a-z]{2})$#", "1397/09/21", [])

**Comment by dena-a** [comment]
The method does not support all php date formats; and there is no any exceptions.

**Comment by morilog** [comment]
Yes, that method is experimental and not covers all php date format. I will work on this method in my free time.
