### ISSUE TITLE
پشتیبانی از لاراول 5.8

### ISSUE THREAD

**Issue by mdhosseini** [morilog/jalali#67]
سلام
لاراول نسخه 5.8 دیروز منتشر شده برای این ورژن به روز رسانی میاد؟
ضمن اینکه یکی از تغییرات ورژن جدید تغییر ورژن کاربن هست که به ورژن 2 به روز رسانی شده

**Comment by morilog** [comment]
از نسخه ۳ به بعد هیچ وابستگی به فریمورک خاصی وجود ندارد. و در هر پروژه php که حداقل‌ها رعایت بشه، قابل استفاده‌ست

**Comment by mdhosseini** [comment]
ممنون بابت پاسختون
ولی موقع نصب در لاراول ورژن 5.8 خطای زیر رو داره
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install morilog/jalali v3.0.13
    - Conclusion: don't install morilog/jalali v3.0.12
    - Conclusion: don't install morilog/jalali v3.0.11
    - Conclusion: don't install morilog/jalali v3.0.10
    - Conclusion: don't install morilog/jalali v3.0.9
    - Conclusion: don't install morilog/jalali v3.0.8
    - Conclusion: don't install morilog/jalali v3.0.7
    - Conclusion: don't install morilog/jalali v3.0.6
    - Conclusion: don't install morilog/jalali v3.0.5
    - Conclusion: don't install morilog/jalali v3.0.4
    - Conclusion: don't install morilog/jalali v3.0.3
    - Conclusion: don't install morilog/jalali v3.0.2
    - Conclusion: don't install morilog/jalali v3.0.1
    - Conclusion: remove nesbot/carbon 2.14.0
    - Installation request for morilog/jalali 3.* -> satisfiable by morilog/jalali[v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9].
    - Conclusion: don't install nesbot/carbon 2.14.0
    - morilog/jalali v3.0.0 requires nesbot/carbon ^1.21 -> satisfiable by nesbot/carbon[1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2].
    - Can only install one of: nesbot/carbon[1.26.3, 2.14.0].
    - Can only install one of: nesbot/carbon[1.26.4, 2.14.0].
    - Can only install one of: nesbot/carbon[1.27.0, 2.14.0].
    - Can only install one of: nesbot/carbon[1.28.0, 2.14.0].
    - Can only install one of: nesbot/carbon[1.29.0, 2.14.0].
    - Can only install one of: nesbot/carbon[1.29.1, 2.14.0].
    - Can only install one of: nesbot/carbon[1.29.2, 2.14.0].
    - Can only install one of: nesbot/carbon[1.30.0, 2.14.0].
    - Can only install one of: nesbot/carbon[1.31.0, 2.14.0].
    - Can only install one of: nesbot/carbon[1.31.1, 2.14.0].
    - Can only install one of: nesbot/carbon[1.32.0, 2.14.0].
    - Can only install one of: nesbot/carbon[1.33.0, 2.14.0].
    - Can only install one of: nesbot/carbon[1.34.0, 2.14.0].
    - Can only install one of: nesbot/carbon[1.34.1, 2.14.0].
    - Can only install one of: nesbot/carbon[1.34.2, 2.14.0].
    - Can only install one of: nesbot/carbon[1.34.3, 2.14.0].
    - Can only install one of: nesbot/carbon[1.34.4, 2.14.0].
    - Can only install one of: nesbot/carbon[1.35.0, 2.14.0].
    - Can only install one of: nesbot/carbon[1.35.1, 2.14.0].
    - Can only install one of: nesbot/carbon[1.36.0, 2.14.0].
    - Can only install one of: nesbot/carbon[1.36.1, 2.14.0].
    - Can only install one of: nesbot/carbon[1.36.2, 2.14.0].
    - Can only install one of: nesbot/carbon[1.21.0, 2.14.0].
    - Can only install one of: nesbot/carbon[1.22.0, 2.14.0].
    - Can only install one of: nesbot/carbon[1.22.1, 2.14.0].
    - Can only install one of: nesbot/carbon[1.23.0, 2.14.0].
    - Can only install one of: nesbot/carbon[1.24.0, 2.14.0].
    - Can only install one of: nesbot/carbon[1.24.1, 2.14.0].
    - Can only install one of: nesbot/carbon[1.24.2, 2.14.0].
    - Can only install one of: nesbot/carbon[1.25.0, 2.14.0].
    - Can only install one of: nesbot/carbon[1.26.0, 2.14.0].
    - Can only install one of: nesbot/carbon[1.26.1, 2.14.0].
    - Can only install one of: nesbot/carbon[1.26.2, 2.14.0].
    - Installation request for nesbot/carbon (locked at 2.14.0) -> satisfiable by nesbot/carbon[2.14.0].

**Comment by morilog** [comment]
لاراول اومده minimum-stablity رو گذاشته روی dev و این یعنی پکیج‌های غیراستیبل رو هم داره نصب میکنه من جمله این ورژن کربن. فعلا منم گذاشتم روی dev تا وقتی گزارشی نشده از کسی.
از ورژن 3.1.1 به بعد بدون مشکل روی لاراول ۵.۸ نصب میشه
