### ISSUE TITLE
نمایش روز هفته

### ISSUE THREAD

**Issue by vahidalvandi** [morilog/jalali#68]
سلام چطوری روز هفته را بدست بیارم مثلا امروز سه شنبه است ؟

**Comment by thearsalan** [comment]
You can use %A key if you're formatting the Jalalian object.

Also a simple helper method to handle this exact use case has been added to the list of available methods, for which, a pull request has been sent now.

**Comment by thearsalan** [comment]
> سلام چطوری روز هفته را بدست بیارم مثلا امروز سه شنبه است ؟

You can use %A key if you're formatting the Jalalian object. Please checkout the documentation for a better reference.

There's also the getDayOfWeek() method on the Jalalian object which gives you the index of the day in the Jalali week.

For instance, Jalalian::now()->getDayOfWeek() returns 6, which represents Friday, the 6th element in the Jalali week array.
