### ISSUE TITLE
5th month name

### ISSUE THREAD

**Issue by sajjadrad** [morilog/jalali#7]
5th month name is مرداد in official jalali calendar but in this package sallar used امرداد (with better meaning). Is it possible to change it to official name?

**Comment by morilog** [comment]
Yes, it would be changed. I try to change month name to `مرداد‍` soon.

**Comment by sajjadrad** [comment]
Thank you

**Comment by morilog** [comment]
this issue fixed in `v2.0.1`

**Comment by sajjadrad** [comment]
Thank you

**Comment by sajjadrad** [comment]
Can you change this month name in version 1.* too?

Thanks.

**Comment by sajjadrad** [comment]
@morilog

**Comment by morilog** [comment]
i've done it , try `composer update`

**Comment by sajjadrad** [comment]
Thanks again ;)

**Comment by sajjadrad** [comment]
@morilog There is no changes for v1.* :( please tag these changes to v1.*

Thanks

**Comment by morilog** [comment]
https://github.com/morilog/jalali/tree/v1.1-1-g80a8193

**Comment by sajjadrad** [comment]
@morilog After updating composer there no new changes, did you update packagist for get new changes from github?
