### ISSUE TITLE
باگ در روز اول هر ماه

### ISSUE THREAD

**Issue by sajaddp** [morilog/jalali#76]
سلام
آقاجان پکیج باگ داره و روز اول هر ماه اطلاعات اشتباه میاره!
این موضوع هم فقط مربوط به روز اول هست و از روز دوم ماه شمسی نرمال کار می کنه

**Comment by morilog** [comment]
سلام
چه باگی داره دقیقا؟ چه اطلاعاتی رو اشتباه نشون میده و چه اطلاعاتی رو باید به جاش نشون بده؟

**Comment by sajaddp** [comment]
<div dir="rtl">
روز اول و آخر هرماه تبدیل تاریخ ها اشتباه انجام میشه.
این موضوع رو بنده در چندماه گذشته مرتب برخورد کردم.
برای مثال اول اردیبهشت امسال تاریخ هایی که مربوط به January 2019 بود رو اشتباه تبدیل می کرد و همچنین در ماه های 31 روزه در اول ماه بعد تاریخ هایی که مربوط به روز 31 ام بوده رو اشتباه تبدیل می کنه.
همون طور که گفتم در چندماه گذشته برخورد کردم روی سرورهای مختلف و پروژه های گوناگونی که برپایه لاراول بود این مسئله رخ میده.
</div>

**Comment by amirGhotb** [comment]
سلام.من این مسئله رو الان روی پروژم چک کردم و همین مشکل رو داشت
متاسفانه الان میبینم آمار و ارقام سایتم این چند وقت دقیق نبوده !!!

**Comment by sajaddp** [comment]
یک مورد دیگه اینکه قطعه کد زیر رو در نظر بگیرید:
```
$forge = Jalalian::forge("-3 months");
$forge->format('y-m');

$forge_2 = Jalalian::forge("-4 months");
$forge_2 ->format('y-m');
÷÷÷
اگر زمان سرور رو برای 1 اردیبهشت تنظیم کنید و تست بگیرید در خروجی اشکال کار مشخص میشه.

**Comment by sajaddp** [comment]
@morilog عزیز این مشکل حل شده؟

**Comment by morilog** [comment]
این مورد رو تست نکردم ولی لطفا از متدهای modifier مثل subMonth استفاده کنید مشکلتون حل میشه
