### ISSUE TITLE
It returns null when using in getCreatedAtAttribute

### ISSUE THREAD

**Issue by behzadcym** [morilog/jalali#77]
سلام 
مشکلی که دارم اینه که وقتی از این پکیج توی مدل استفاده میکنم خالی برمیگردونه
  هست getCreatedAtAttribure منظورم متود
البته قبلا استفاده کرده بودم و مشکلی نداشت

**Comment by morilog** [comment]
اولا این پکیج مستقل از فریمورک خاصی داره کار میکنه
ثانیا من نمیدونم شما تو کدت چی نوشتی که کار نمیکنه
