### ISSUE TITLE
مشکل در کم کردن ماه از تاریخ subMonths

### ISSUE THREAD

**Issue by DigiGostar** [morilog/jalali#78]
```
$now = Jalalian::now();
$now->getYear();
$now->getMonth();
$thisDate = new Jalalian($now->getYear(), $now->getMonth(), 1);
$month = array($thisDate);
for ($i = 1; $i < 13; $i++) {
    array_push($month, $thisDate->subMonths($i));
}
print_r($month);
```

خروجی:

--
[0] => Morilog\Jalali\Jalalian Object
  | (
  | [year:Morilog\Jalali\Jalalian:private] => 1398
  | [month:Morilog\Jalali\Jalalian:private] => **2**
  | [day:Morilog\Jalali\Jalalian:private] => 1
  | )
  |  
  | [1] => Morilog\Jalali\Jalalian Object
  | (
  | [year:Morilog\Jalali\Jalalian:private] => 1398
  | [month:Morilog\Jalali\Jalalian:private] => **1**
  | [day:Morilog\Jalali\Jalalian:private] => 1
  | )
  |  
  | [2] => Morilog\Jalali\Jalalian Object
  | (
  | [year:Morilog\Jalali\Jalalian:private] => **1398**
  | [month:Morilog\Jalali\Jalalian:private] => **2**
  | [day:Morilog\Jalali\Jalalian:private] => 1
  | )
  |  
  | [3] => Morilog\Jalali\Jalalian Object
  | (
  | [year:Morilog\Jalali\Jalalian:private] => **1398**
  | [month:Morilog\Jalali\Jalalian:private] => **3**
  | [day:Morilog\Jalali\Jalalian:private] => 1
  | )
  |  
  | [4] => Morilog\Jalali\Jalalian Object
  | (
  | [year:Morilog\Jalali\Jalalian:private] => **1398**
  | [month:Morilog\Jalali\Jalalian:private] => **4**
  | [day:Morilog\Jalali\Jalalian:private] => 1
  | )

در مرحله اول یک ماه کم کرد ولی در مراحل بعدی فور اصلا درست کار نمیکنه و تازه ماه اضافه میکنه !

**Comment by dena-a** [comment]
The problem has fixed on #73 ; @morilog please close the  issue.
