### ISSUE TITLE
مشکل در پیدا کردن روز اول ماه بین شمسی و میلادی

### ISSUE THREAD

**Issue by hekmatnajafi** [morilog/jalali#82]
مثلا من میخوام یک مپ درست کنم طوری که روز های هر ماه را نام روز اش معلوم کنم:
0 => شنبه
1 => یکشنبه
ولی از انجای که شروع اول ماه شمسی با میلادی فرق داره این نمیتونه تشخیص بده.
مثلا:
ماه شمسی روز شنبه اول ماه اش است ولی ماه میلادی همان ماه را روز دوشنبه شروع میکنه.
تا جایی که من فهمیدم jdate() همیشه تاریخ میلادی میگیره ولی اگه بتونه تاریخ فارسی را هم بگیره این مشکل را میشه حل کرد

**Comment by morilog** [comment]
میتونی از متد `fromFormat استفاده کنی برای اینکار و یه تایم‌استمپ شمسی بهش پاس بدی

**Comment by coretmapp** [comment]
مهندس این خطا واسه چیه
منطق برنامه دورسته
Undefined index: year
