### ISSUE TITLE
چطور میشه نام ماه را بدست آورد 

### ISSUE THREAD

**Issue by vahidalvandi** [morilog/jalali#84]
سلام مثلا 
۵
مرداد

**Comment by rezaxdi** [comment]
سلام
یکی از خوبی های این کتابخونه اینه که از اسامی فارسی استفاده نشده که خیلی جاها فوق العاده دردسر هست اگر کتابخونه ای از کلمات فارسی داخلش استفاده کرده باشه. پس برای پیدا کردن نام روز ها و همچنین ماه ها باید خودتون شماره ماه رو چک کنید اگه مثلا ۵ بود بنویسید مرداد
