### ISSUE TITLE
Jalalian::fromFormat() throws exception in case of invalid input

### ISSUE THREAD

**Issue by hshahdoost** [morilog/jalali#87]
What I'm about to say is more of a feature, As I'm using this library, I have noticed that there is no way to check the validation of our string date before using `fromFormat` method. And this method directly throws an `ErrorException` (which is pretty general) in case there is anything wrong with the user input, I believe it would be a lot better if there was a method which could simply validate a given string date with a format, to avoid general exception handling.

PS: Thanks a lot for taking time and putting effort into this library.

**Comment by hsyir** [comment]
@hshahdoost good idea, i have this challenge with this as you have.
