### ISSUE TITLE
parameters with a class type hint can only 

### ISSUE THREAD

**Issue by famousman** [morilog/jalali#88]
Fatal error: Default value for parameters with a class type hint can only be NULL in Jalalian.php on line 49

سلام
من این خطا رو میگیرم.  زمانیکه از require_once استفاده می کنم

**Comment by morilog** [comment]
خط ۴۹ که کار خاصی رخ نمیده. از چه ورژن php و چه ورژنی از کتابخونه داری استفاده میکنی؟
