### ISSUE TITLE
CheckDate is always return true 

### ISSUE THREAD

**Issue by omer-jan** [morilog/jalali#91]
Hi Dears,
please help 
echo(\Morilog\Jalali\CalendarUtils::checkDate(1391, 2, 30, true));
echo(\Morilog\Jalali\CalendarUtils::checkDate(2019, 2, 30, true));
 according to documentation the first line should return true and the second line should return false but both return true .

**Comment by morilog** [comment]
The documents are not consistent. this package supports to 3000 jalali year. according to this, both dates are correct jalali dates
