### ISSUE TITLE
مشکل تعداد روز های آخرین ماه سال کبیسه

### ISSUE THREAD

**Issue by reza-akbari** [morilog/jalali#92]
سلام
تعداد روزهای ماه 12ام همیشه 29 درنظر گرفته شده.

https://github.com/morilog/jalali/blob/695eb6bdffd990aab6d4f4013f26d75fce1c74a4/src/CalendarUtils.php#L429

 باید مثل متد
jalaliMonthLength 
سال کبیسه هم چک بشه

باتشکر و سپاس بابت این پکیج

**Comment by morilog** [comment]
سلام
ممنون بابت گزارش. اگه خودتون فقط میکنید یه merge reques بفرستید اگر نه که
باید وقت کنم درستش کنم
*Morteza Parvini* / Software Developer

[image: Twitter]  <https://twitter.com/imorteza> [image: LinkedIn]
<https://www.linkedin.com/in/morilog>

**Comment by reza-akbari** [comment]
سلام
بله حتما امشب میفرستم
