### ISSUE TITLE
Problem with construct

### ISSUE THREAD

**Issue by EhsanJamshidi** [morilog/jalali#94]
PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /home/public_html/vendor/morilog/jalali/src/Jalalian.php on line 49

how this errors show up and how can solve it

**Comment by morilog** [comment]
Look at [this lines ](https://github.com/morilog/jalali/blob/ae040b5659c04933f8d7423f1fabaa1dd168d62b/src/Jalalian.php#L45) . you should pass suitable values to the constructor.
