### ISSUE TITLE
Request: The week of month method is needed

### ISSUE THREAD

**Issue by mirzacodenevis** [morilog/jalali#97]
Hi like carbon the weekOfMonth property is needed

**Comment by morilog** [comment]
Can you add the method and make a merge request?

**Comment by rezarabbbani** [comment]
Yes let me see if i can do it later on today.

**Comment by rezarabbbani** [comment]
I'm afraid I can't make a merge request. by the way I wrote the method
`
    public function getWeekOfMonth(): int
    {
        $week = 1;
        for ($i = 1; $i <= $this->getMonthDays(); $i++) {
            if ($this->addDays($i)->isEndOfWeek())
                $week++;
            if ($this->day == $i)
                return $week;
        }
    }
`
I appreciate you add it if its correct

**Comment by morilog** [comment]
There is not any fear. you can write code and test. make MR when all tests pass.
BTW the problem might be solved by bellow code:
`$weekOfMonth = (int) ceil($this->day / 7)`

**Comment by rezarabbbani** [comment]
`$weekOfMonth = (int) ceil($this->day / 7)` doesn't work correctly as some months are 5 weeks and others are 4

**Comment by hshahdoost** [comment]
The following would get the job done
```
$offset = (new Jalalian($this->year, $this->month, 1))->getDayOfWeek();
$weekOfMonth = ceil(($offset + $this->day) / 7);
```

**Comment by reza972** [comment]
@hshahdoost  
No it doesnt work properly test with these values
```
$offset = (new Jalalian(1398, 3, 1))->getDayOfWeek();
$weekOfMonth =ceil(($offset + 3) / 7);
```
It should return 2 but returns 1, also with 31 as day value should return 6 but returns 5

**Comment by reza972** [comment]
@hshahdoost 
It works fine tnx

**Comment by morilog** [comment]
@hshahdoost please make a merge request and add `getWeekOfMonth()` method
